apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: ecaverolevano/serviciosapiseguridad:v2.#{Build.BuildId}#
      ports:
        - containerPort: 80
      env:
        - name: ConnectionStrings__ConexionDB
          value: Server=mssql-service;Database=Seguridad;User=sa;Password=s0p0rt3$5
