apiVersion: apps/v1
kind: Deployment
metadata:
	name: microservice-libreria-deploy
	labels:
		name: microservice-libreria-deploy
		app: microservice
spec:
	replicas: 2
	selector:
		matchLabels:
			app: microservice-libreria
			type: microservice
	template:
		metadata:
			name: microservice-libreria-pod
			labels:
				app: microservice-libreria
				type: microservice
		spec:
			container:
			- name: microservice-libreria-app
				image: ecaverolevano/serviciosapilibreria:latest
				ports:
				- containerPort: 80
				env:
				- name: MongoDB__ConnectionString
				  value: mongodb://ecaverolevano:erickcl19@mongo-service:27017