apiVersion: v1
kind: Pod
metadata:
	name: mongo-pod
	labels:
		app: microservice-libreria
		name: mongo-pod
spec:
	container:
	- name: mongo
	  image: mongo:4.2.12
	  command:
	  - /bin/bash
	  - -c
	  env:
	  - name: MONGO_INITDB_ROOT_USERNAME
		value: "ecaverolevano"
	  - name: MONGO_INITDB_ROOT_PASSWORD
		value: "erickcl19"
	  ports:
		- containerPort: 27017