apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app:  microservice
spec:
    replicas: 1
    selector:
      matchLabels:
        app: microservice-libreria
        name: mongo-pod
    template:
        metadata:
          name: mongo-pod
          labels:
            app: microservice-libreria
            name: mongo-pod
        spec:
          containers:
            - name: mongo
              image: mongo:latest
              env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: "ecaverolevano"
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: "S0p0rt3$5"
              ports:
                - containerPort: 27017